[package]
name = "issuefer"
version = "0.1.0"
authors = ["Hans-Peter Schadler <hps@abyle.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
regex = "1"
